#!/usr/bin/env perl

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

# cwd in @INC is harmful:
# http://www.nntp.perl.org/group/perl.perl5.porters/2010/08/msg162729.html
no lib '.';

use strict;
use warnings;

use English qw(-no_match_vars);

while (<STDIN>) {
    s/([[:alpha:]])/rand(2) >= 1 ? "\L$1" : "\U$1"/ge;
    print or die $ERRNO;
}

# vim:ts=4 sts=4 sw=4 et
